[package]
name = "godot-rust-script"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
godot.workspace = true
itertools.workspace = true
abi_stable.workspace = true
rand.workspace = true
cfg-if.workspace = true

hot-lib-reloader = { workspace = true, optional = true }
process_path = { workspace = true, optional = true }

godot-rust-script-derive.workspace = true

[dev-dependencies]
tests-scripts-lib = { path = "../tests-scripts-lib", features = ["hot-reload"] }

[features]
default = ["hot-reload"]
hot-reload = ["dep:process_path", "dep:hot-lib-reloader"]